//! Combinatorial coverage on `firewall::render_anchor`. Pinning the
//! anchor body shape directly because no verb wires the renderer until
//! 2.4 (create-side firewall step), and the matrix here is content-shape
//! (empty hosts vs populated, ordering, structural invariants like
//! loopback-before-block) which is awkward to drive through the CLI
//! surface. Same in-tree precedent and justification as
//! `tests/macos_host_machine.rs`'s per-variant pins.

use tenant::firewall::render_anchor;

#[test]
fn render_with_no_hosts_emits_bare_empty_table() {
    let body = render_anchor("dev", &[]);
    assert_eq!(
        body,
        "# PF anchor for tenant 'dev' \u{2014} generated by 'tenant create'; \
         do not edit by hand\n\
         \n\
         table <allowed> persist { }\n\
         \n\
         pass out quick on lo0 user dev\n\
         pass out quick proto tcp from any to <allowed> port 443 user dev\n\
         block out quick proto { tcp udp } from any to any user dev\n",
    );
}

#[test]
fn render_with_one_host_uses_backslash_continuation() {
    let body = render_anchor("dev", &["api.anthropic.com".to_string()]);
    assert!(
        body.contains("table <allowed> persist { \\\n  api.anthropic.com \\\n}\n"),
        "expected backslash-continued single-host table, got body:\n{body}"
    );
}

#[test]
fn render_with_multiple_hosts_preserves_input_order() {
    // Operator groups hosts in profile.toml in a meaningful order (e.g.
    // provider, ecosystem). The rendered anchor must respect that order
    // so diffs against a hand-reviewed profile stay readable.
    let body = render_anchor(
        "dev",
        &[
            "api.anthropic.com".to_string(),
            "github.com".to_string(),
            "crates.io".to_string(),
        ],
    );
    assert!(
        body.contains(
            "table <allowed> persist { \\\n  \
             api.anthropic.com \\\n  \
             github.com \\\n  \
             crates.io \\\n}\n"
        ),
        "expected hosts in caller order, got body:\n{body}"
    );
}

#[test]
fn render_emits_loopback_pass_before_catchall_block() {
    // Load-bearing invariant: without lo0 pass-before-block, tenants
    // can't reach localhost-bound services (host's MySQL, Redis,
    // dev-mode web servers). PF rules match all interfaces by default
    // including lo0, so the catchall block would otherwise drop
    // loopback traffic too.
    let body = render_anchor("dev", &[]);
    let loopback_idx = body
        .find("pass out quick on lo0 user dev")
        .expect("loopback pass rule must be present");
    let block_idx = body
        .find("block out quick proto { tcp udp } from any to any user dev")
        .expect("catchall block rule must be present");
    assert!(
        loopback_idx < block_idx,
        "loopback pass at {loopback_idx} must come before block at {block_idx} \
         (without this ordering tenants cannot reach localhost services)"
    );
}

#[test]
fn render_block_rule_scoped_to_tenant_via_user_keyword() {
    // The catchall block must carry the tenant's user keyword so that
    // tenant traffic is what gets dropped — not the host's traffic, not
    // every UID's traffic. The user keyword binds PF's match to the
    // socket's owning UID.
    let body = render_anchor("smoketest", &[]);
    assert!(
        body.contains("block out quick proto { tcp udp } from any to any user smoketest"),
        "block rule must scope to tenant 'smoketest' via user keyword, got body:\n{body}"
    );
}
