//! Combinatorial coverage on `firewall::render_anchor`. Pinning the
//! anchor body shape directly because the inbound/egress section shapes
//! (empty hosts vs populated, ordering, the three inbound forms, and
//! structural invariants like the egress section staying constant across
//! inbound postures) are content-shape facts awkward to drive through the
//! CLI surface. Same in-tree precedent and justification as
//! `tests/macos_host_machine.rs`'s per-variant pins.

use tenant::firewall::{InboundRules, anchor_is_permissive, render_anchor};

// Locked (restricted + empty ports) is the migration default — every
// non-inbound-aware call site renders this. Keep it close to hand.
fn locked() -> InboundRules {
    InboundRules::Restricted(vec![])
}

#[test]
fn render_with_no_hosts_emits_bare_empty_table() {
    let body = render_anchor("dev", &[], locked());
    assert_eq!(
        body,
        "# PF anchor for tenant 'dev' \u{2014} generated by 'tenant create'; \
         do not edit by hand\n\
         \n\
         table <allowed> persist { }\n\
         \n\
         block drop in quick on lo0 proto tcp from any to any user dev flags S/SA\n\
         pass out quick on lo0 proto tcp from any to any user dev no state\n\
         pass out quick proto tcp from any to <allowed> port 443 user dev\n\
         block out quick proto { tcp udp } from any to any user dev\n",
    );
}

#[test]
fn render_with_one_host_uses_backslash_continuation() {
    let body = render_anchor("dev", &["api.anthropic.com".to_string()], locked());
    assert!(
        body.contains("table <allowed> persist { \\\n  api.anthropic.com \\\n}\n"),
        "expected backslash-continued single-host table, got body:\n{body}"
    );
}

#[test]
fn render_with_multiple_hosts_preserves_input_order() {
    // Operator groups hosts in profile.toml in a meaningful order (e.g.
    // provider, ecosystem). The rendered anchor must respect that order
    // so diffs against a hand-reviewed profile stay readable.
    let body = render_anchor(
        "dev",
        &[
            "api.anthropic.com".to_string(),
            "github.com".to_string(),
            "crates.io".to_string(),
        ],
        locked(),
    );
    assert!(
        body.contains(
            "table <allowed> persist { \\\n  \
             api.anthropic.com \\\n  \
             github.com \\\n  \
             crates.io \\\n}\n"
        ),
        "expected hosts in caller order, got body:\n{body}"
    );
}

#[test]
fn render_emits_loopback_egress_pass_before_catchall_block() {
    // Load-bearing invariant: without the lo0 egress pass-before-block,
    // tenants can't reach localhost-bound services (host's MySQL, Redis,
    // dev-mode web servers). PF rules match all interfaces by default
    // including lo0, so the catchall block would otherwise drop loopback
    // egress too.
    let body = render_anchor("dev", &[], locked());
    let loopback_idx = body
        .find("pass out quick on lo0 proto tcp from any to any user dev no state")
        .expect("loopback egress pass rule must be present");
    let block_idx = body
        .find("block out quick proto { tcp udp } from any to any user dev")
        .expect("catchall block rule must be present");
    assert!(
        loopback_idx < block_idx,
        "loopback egress pass at {loopback_idx} must come before block at {block_idx} \
         (without this ordering tenants cannot reach localhost services)"
    );
}

#[test]
fn render_block_rule_scoped_to_tenant_via_user_keyword() {
    // The catchall block must carry the tenant's user keyword so that
    // tenant traffic is what gets dropped — not the host's traffic, not
    // every UID's traffic. The user keyword binds PF's match to the
    // socket's owning UID.
    let body = render_anchor("smoketest", &[], locked());
    assert!(
        body.contains("block out quick proto { tcp udp } from any to any user smoketest"),
        "block rule must scope to tenant 'smoketest' via user keyword, got body:\n{body}"
    );
}

// ── inbound loopback section (cycle 24) ──────────────────────────────

#[test]
fn render_locked_omits_inbound_pass() {
    // Restricted + empty ports = locked: no inbound pass at all, just the
    // block-in and the no-state egress pass. A locked tenant accepts no
    // loopback inbound from anyone (not even itself on its own ports).
    let body = render_anchor("dev", &[], InboundRules::Restricted(vec![]));
    assert!(
        !body.contains("pass in quick on lo0"),
        "locked inbound must omit the inbound pass, got body:\n{body}"
    );
    assert!(
        body.contains("block drop in quick on lo0 proto tcp from any to any user dev flags S/SA\n"),
        "locked inbound must keep the block-in, got body:\n{body}"
    );
    assert!(
        body.contains("pass out quick on lo0 proto tcp from any to any user dev no state\n"),
        "locked inbound must keep the no-state egress pass, got body:\n{body}"
    );
}

#[test]
fn render_restricted_single_port_emits_bare_port() {
    let body = render_anchor("dev", &[], InboundRules::Restricted(vec![3000]));
    assert!(
        body.contains(
            "pass in quick on lo0 proto tcp from any to any port 3000 user dev no state\n"
        ),
        "single declared port renders bare (no list braces), got body:\n{body}"
    );
}

#[test]
fn render_restricted_multi_port_uses_pf_list_in_declared_order() {
    // Operator declares ports in a meaningful order; preserve it so the
    // rendered anchor diffs cleanly against the profile.
    let body = render_anchor("dev", &[], InboundRules::Restricted(vec![8080, 3000]));
    assert!(
        body.contains(
            "pass in quick on lo0 proto tcp from any to any port { 8080, 3000 } user dev no state\n"
        ),
        "multi-port renders as a pf list in declared order, got body:\n{body}"
    );
}

#[test]
fn render_restricted_with_ports_orders_pass_in_before_block_in() {
    // The inbound pass must precede the block-in (pf first-match-wins via
    // quick): otherwise the block-in would drop the declared-port SYN
    // before the pass could match it.
    let body = render_anchor("dev", &[], InboundRules::Restricted(vec![3000]));
    let pass_idx = body
        .find("pass in quick on lo0 proto tcp from any to any port 3000 user dev no state")
        .expect("inbound pass must be present");
    let block_idx = body
        .find("block drop in quick on lo0 proto tcp from any to any user dev flags S/SA")
        .expect("inbound block must be present");
    assert!(
        pass_idx < block_idx,
        "inbound pass at {pass_idx} must precede block-in at {block_idx}"
    );
}

#[test]
fn render_permissive_collapses_inbound_to_single_pass() {
    // Permissive replaces the whole inbound section with one all-ports
    // pass; no block-in, no separate egress line.
    let body = render_anchor("dev", &[], InboundRules::Permissive);
    assert!(
        body.contains("pass quick on lo0 proto tcp from any to any user dev no state\n"),
        "permissive emits the single collapsed pass, got body:\n{body}"
    );
    assert!(
        !body.contains("block drop in"),
        "permissive omits the block-in, got body:\n{body}"
    );
    assert!(
        !body.contains("pass in quick on lo0"),
        "permissive omits the restricted-form inbound pass, got body:\n{body}"
    );
}

#[test]
fn render_egress_section_constant_across_inbound_postures() {
    // Negative pin: the egress allowlist gate + catchall block are
    // inbound-axis-independent. Only the loopback section changes.
    let egress = "pass out quick proto tcp from any to <allowed> port 443 user dev\n\
                  block out quick proto { tcp udp } from any to any user dev\n";
    for inbound in [
        InboundRules::Restricted(vec![]),
        InboundRules::Restricted(vec![3000, 8080]),
        InboundRules::Permissive,
    ] {
        let body = render_anchor("dev", &["api.example.com".to_string()], inbound);
        assert!(
            body.ends_with(egress),
            "egress section must be constant across inbound postures, got body:\n{body}"
        );
    }
}

#[test]
fn render_is_deterministic() {
    let a = render_anchor(
        "dev",
        &["x.example".to_string()],
        InboundRules::Restricted(vec![3000, 8080]),
    );
    let b = render_anchor(
        "dev",
        &["x.example".to_string()],
        InboundRules::Restricted(vec![3000, 8080]),
    );
    assert_eq!(a, b, "render_anchor must be deterministic");
}

// ============================================================
// anchor_is_permissive — structural detection of a widened anchor
// ============================================================
//
// Doctor reads the on-disk anchor body to learn the CURRENT inbound
// posture (no state file). A permissive anchor carries the single
// `pass quick on lo0 … no state` line (no `in`/`out` keyword); restricted
// and locked anchors never do. Detection is structural — the renderer is
// deterministic, but a hand-edit could re-order lines, so match on the
// permissive line's presence, not byte-exact.

#[test]
fn anchor_is_permissive_true_for_permissive_render() {
    let body = render_anchor("dev", &[], InboundRules::Permissive);
    assert!(
        anchor_is_permissive(&body),
        "permissive render must classify as permissive, got body:\n{body}"
    );
}

#[test]
fn anchor_is_permissive_false_for_locked_render() {
    let body = render_anchor("dev", &[], locked());
    assert!(
        !anchor_is_permissive(&body),
        "locked render must not classify as permissive, got body:\n{body}"
    );
}

#[test]
fn anchor_is_permissive_false_for_restricted_with_ports() {
    let body = render_anchor("dev", &[], InboundRules::Restricted(vec![3000, 8080]));
    assert!(
        !anchor_is_permissive(&body),
        "restricted-with-ports render must not classify as permissive, got body:\n{body}"
    );
}
