//! PF anchor + `/etc/pf.conf` line ops. Pure functions over PF syntax.

pub const ANCHOR_DIR: &str = "/etc/pf.anchors";

pub const PF_CONF: &str = "/etc/pf.conf";

/// Fixed-name backup of `/etc/pf.conf`. Overwritten on each invocation
/// (deterministic recovery; no timestamped backups). The `tenant-`
/// prefix keeps it distinct from any host backup convention (e.g.
/// `pf.conf.bak`).
pub const PF_CONF_BACKUP: &str = "/etc/pf.conf.tenant-backup";

pub fn tenant_anchor_path(name: &str) -> String {
    format!("{ANCHOR_DIR}/{}", tenant_anchor_name(name))
}

pub fn tenant_anchor_name(name: &str) -> String {
    format!("tenant-{name}")
}

fn anchor_line(anchor: &str) -> String {
    format!("anchor \"{anchor}\"")
}

fn load_anchor_line(anchor: &str) -> String {
    format!("load anchor \"{anchor}\" from \"{ANCHOR_DIR}/{anchor}\"")
}

/// `true` iff both the `anchor` and `load anchor` lines for tenant
/// `name` are present in `content`. Line-level (not substring): the
/// bare `anchor "X"` line is a substring of `load anchor "X" from …`,
/// so a substring check would falsely report the anchor line as
/// present when only the load line exists.
pub fn is_anchor_referenced(content: &str, name: &str) -> bool {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut has_anchor = false;
    let mut has_load = false;
    for line in content.lines() {
        if line == target_anchor {
            has_anchor = true;
        } else if line == target_load {
            has_load = true;
        }
    }
    has_anchor && has_load
}

/// Return `content` with both anchor + load-anchor lines for tenant
/// `name` ensured present. Idempotent; appends only missing line(s).
pub fn ensure_anchor_ref(content: &str, name: &str) -> String {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut has_anchor = false;
    let mut has_load = false;
    for line in content.lines() {
        if line == target_anchor {
            has_anchor = true;
        } else if line == target_load {
            has_load = true;
        }
    }
    if has_anchor && has_load {
        return content.to_string();
    }
    // Normalize trailing newline state so appended lines land cleanly.
    let mut out = content.trim_end_matches('\n').to_string();
    if !out.is_empty() {
        out.push('\n');
    }
    if !has_anchor {
        out.push_str(&target_anchor);
        out.push('\n');
    }
    if !has_load {
        out.push_str(&target_load);
        out.push('\n');
    }
    out
}

/// Return `content` with both anchor + load-anchor lines for tenant
/// `name` removed. Idempotent; absent lines silently no-op.
pub fn remove_anchor_ref(content: &str, name: &str) -> String {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut out = String::new();
    for line in content.split_inclusive('\n') {
        let trimmed = line.trim_end_matches('\n');
        if trimmed != target_anchor && trimmed != target_load {
            out.push_str(line);
        }
    }
    out
}

/// Render the PF anchor body for the named tenant with the given runtime
/// hosts. Output is the verbatim file content for
/// `/etc/pf.anchors/tenant-<name>`:
///
/// 1. Header comment naming the tenant.
/// 2. `table <allowed> persist { … }` — backslash-continued when
///    populated, single-line `{ }` when empty.
/// 3. `pass out quick on lo0 user <name>` — loopback MUST come before
///    the catchall block (without this, tenants can't reach localhost
///    services like a host-run MySQL or Redis).
/// 4. `pass out quick proto tcp from any to <allowed> port 443 user <name>`
///    — egress allowlist gate.
/// 5. `block out quick proto { tcp udp } from any to any user <name>`
///    — catchall scoped to the tenant's UID via PF's `user` keyword.
///
/// Host order is preserved from `hosts` so the rendered anchor's diff
/// is stable against the operator's profile.toml grouping.
pub fn render_anchor(name: &str, hosts: &[String]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# PF anchor for tenant '{name}' \u{2014} generated by 'tenant create'; do not edit by hand\n\n"
    ));
    if hosts.is_empty() {
        out.push_str("table <allowed> persist { }\n");
    } else {
        out.push_str("table <allowed> persist { \\\n");
        for host in hosts {
            out.push_str(&format!("  {host} \\\n"));
        }
        out.push_str("}\n");
    }
    out.push('\n');
    out.push_str(&format!("pass out quick on lo0 user {name}\n"));
    out.push_str(&format!(
        "pass out quick proto tcp from any to <allowed> port 443 user {name}\n"
    ));
    out.push_str(&format!(
        "block out quick proto {{ tcp udp }} from any to any user {name}\n"
    ));
    out
}
