//! PF anchor + `/etc/pf.conf` line ops. Pure functions over PF syntax.

pub const ANCHOR_DIR: &str = "/etc/pf.anchors";

pub const PF_CONF: &str = "/etc/pf.conf";

/// Fixed name, overwritten each run (no timestamped backups); the `tenant-`
/// prefix avoids colliding with a host's own `pf.conf.bak`.
pub const PF_CONF_BACKUP: &str = "/etc/pf.conf.tenant-backup";

pub fn tenant_anchor_path(name: &str) -> String {
    format!("{ANCHOR_DIR}/{}", tenant_anchor_name(name))
}

pub fn tenant_anchor_name(name: &str) -> String {
    format!("tenant-{name}")
}

fn anchor_line(anchor: &str) -> String {
    format!("anchor \"{anchor}\"")
}

fn load_anchor_line(anchor: &str) -> String {
    format!("load anchor \"{anchor}\" from \"{ANCHOR_DIR}/{anchor}\"")
}

/// Line-level, not substring: `anchor "X"` is a substring of
/// `load anchor "X" from …`, so a substring check false-positives.
pub fn is_anchor_referenced(content: &str, name: &str) -> bool {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut has_anchor = false;
    let mut has_load = false;
    for line in content.lines() {
        if line == target_anchor {
            has_anchor = true;
        } else if line == target_load {
            has_load = true;
        }
    }
    has_anchor && has_load
}

pub fn ensure_anchor_ref(content: &str, name: &str) -> String {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut has_anchor = false;
    let mut has_load = false;
    for line in content.lines() {
        if line == target_anchor {
            has_anchor = true;
        } else if line == target_load {
            has_load = true;
        }
    }
    if has_anchor && has_load {
        return content.to_string();
    }
    let mut out = content.trim_end_matches('\n').to_string();
    if !out.is_empty() {
        out.push('\n');
    }
    if !has_anchor {
        out.push_str(&target_anchor);
        out.push('\n');
    }
    if !has_load {
        out.push_str(&target_load);
        out.push('\n');
    }
    out
}

pub fn remove_anchor_ref(content: &str, name: &str) -> String {
    let anchor = tenant_anchor_name(name);
    let target_anchor = anchor_line(&anchor);
    let target_load = load_anchor_line(&anchor);
    let mut out = String::new();
    for line in content.split_inclusive('\n') {
        let trimmed = line.trim_end_matches('\n');
        if trimmed != target_anchor && trimmed != target_load {
            out.push_str(line);
        }
    }
    out
}

/// Resolved by the domain before rendering so `firewall.rs` stays free of
/// `cli`/`profile` deps. `Restricted(vec![])` means locked (no inbound).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InboundRules {
    Permissive,
    Restricted(Vec<u16>),
}

/// A bare profile host resolves to `ports = [443]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EgressHost {
    pub host: String,
    pub ports: Vec<u16>,
}

const DEFAULT_PORTS: &[u16] = &[443];

/// Verbatim body of `/etc/pf.anchors/tenant-<name>`. pf tables can't carry
/// ports, so each distinct port list (verbatim order: `[443, 22]` ≠
/// `[22, 443]`) gets its own table; all tables render first because pf
/// requires definition before use. The loopback `pass out … no state` must
/// precede the catchall block (else tenants can't reach host-run localhost
/// services) and stays `no state`: an auto `keep state` breaks the
/// restricted-port reply path. `block drop in` keeps `flags S/SA` so replies
/// on tenant-initiated connections aren't caught. Order follows the profile
/// so the rendered diff stays stable.
pub fn render_anchor(name: &str, hosts: &[EgressHost], inbound: InboundRules) -> String {
    let default_hosts: Vec<&str> = hosts
        .iter()
        .filter(|h| h.ports.as_slice() == DEFAULT_PORTS)
        .map(|h| h.host.as_str())
        .collect();
    let mut other_groups: Vec<(&[u16], Vec<&str>)> = Vec::new();
    for h in hosts {
        if h.ports.as_slice() == DEFAULT_PORTS {
            continue;
        }
        match other_groups
            .iter_mut()
            .find(|(p, _)| *p == h.ports.as_slice())
        {
            Some((_, group_hosts)) => group_hosts.push(h.host.as_str()),
            None => other_groups.push((h.ports.as_slice(), vec![h.host.as_str()])),
        }
    }

    let mut out = String::new();
    out.push_str(&format!(
        "# PF anchor for tenant '{name}' \u{2014} generated by 'tenant create'; do not edit by hand\n\n"
    ));
    push_table(&mut out, "allowed", &default_hosts);
    for (ports, group_hosts) in &other_groups {
        push_table(&mut out, &table_name(ports), group_hosts);
    }
    out.push('\n');
    out.push_str(&render_inbound_section(name, &inbound));
    out.push_str(&format!(
        "pass out quick proto tcp from any to <allowed> port 443 user {name}\n"
    ));
    for (ports, _) in &other_groups {
        out.push_str(&format!(
            "pass out quick proto tcp from any to <{}> port {} user {name}\n",
            table_name(ports),
            render_port_spec(ports),
        ));
    }
    out.push_str(&format!(
        "block out quick proto {{ tcp udp }} from any to any user {name}\n"
    ));
    out
}

fn push_table(out: &mut String, table: &str, hosts: &[&str]) {
    if hosts.is_empty() {
        out.push_str(&format!("table <{table}> persist {{ }}\n"));
    } else {
        out.push_str(&format!("table <{table}> persist {{ \\\n"));
        for host in hosts {
            out.push_str(&format!("  {host} \\\n"));
        }
        out.push_str("}\n");
    }
}

/// The anchor table a host with these ports renders into.
pub fn egress_table_name(ports: &[u16]) -> String {
    if ports == DEFAULT_PORTS {
        "allowed".to_string()
    } else {
        table_name(ports)
    }
}

fn table_name(ports: &[u16]) -> String {
    let joined = ports
        .iter()
        .map(u16::to_string)
        .collect::<Vec<_>>()
        .join("_");
    format!("allowed_{joined}")
}

/// Structural, not byte-exact, so hand-edits that re-order or re-space lines
/// still match. Only `Permissive` renders the directionless `pass quick on
/// lo0` line; restricted forms always carry `in`/`out`.
pub fn anchor_is_permissive(body: &str) -> bool {
    let needle = "pass quick on lo0 proto tcp from any to any";
    body.lines()
        .any(|line| line.trim_start().starts_with(needle))
}

fn render_inbound_section(name: &str, inbound: &InboundRules) -> String {
    match inbound {
        InboundRules::Permissive => {
            format!("pass quick on lo0 proto tcp from any to any user {name} no state\n")
        }
        InboundRules::Restricted(ports) => {
            let mut section = String::new();
            if !ports.is_empty() {
                section.push_str(&format!(
                    "pass in quick on lo0 proto tcp from any to any port {} user {name} no state\n",
                    render_port_spec(ports)
                ));
            }
            section.push_str(&format!(
                "block drop in quick on lo0 proto tcp from any to any user {name} flags S/SA\n"
            ));
            section.push_str(&format!(
                "pass out quick on lo0 proto tcp from any to any user {name} no state\n"
            ));
            section
        }
    }
}

/// Caller guarantees non-empty.
fn render_port_spec(ports: &[u16]) -> String {
    if ports.len() == 1 {
        ports[0].to_string()
    } else {
        let joined = ports
            .iter()
            .map(u16::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        format!("{{ {joined} }}")
    }
}
